server:
  port: 8189
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 215MB
  jpa:
    hibernate:
      ddl-auto: update


  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/security
    username: ilya
    password: ilya
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

#upoadDir: resources
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect