package com.project.project.requests.admin;

public enum UserUpdateField {
    CASE_ACTIVE_UPDATE,
    CASE_BIRTHDAY_UPDATE,
    CASE_CONFIRM_UPDATE,
    CASE_FIRSTNAME_UPDATE,
    CASE_LASTNAME_UPDATE,
    CASE_PASSWORD_UPDATE,
    CASE_PROFILE_ACCESS_UPDATE,
    CASE_ROLE_UPDATE,

    // BLACKLIST CASES
    CASE_ADD_TO_BLACKLIST,
    CASE_GET_BLACKLIST
}
