package com.project.requests.admin;

public enum UserUpdateField {
    // PROFILE INFO CASES:
    CASE_ACTIVE_UPDATE,
    CASE_BAN,
    CASE_BIRTHDAY_UPDATE,
    CASE_CONFIRM_UPDATE,
    CASE_FIRSTNAME_UPDATE,
    CASE_LASTNAME_UPDATE,
    CASE_GENDER,
    CASE_PASSWORD_UPDATE,
    CASE_PERSONAL_TYPE_UPDATE,
    CASE_PROFILE_ACCESS_UPDATE,
    CASE_ROLE_UPDATE,

    // BLACKLIST CASES:
    CASE_ADD_TO_BLACKLIST,
    CASE_CHECK_IN_BLACKLIST,
    CASE_DELETE_FROM_BLACKLIST,
    CASE_GET_BLACKLIST,

    // PHOTO CASES:
    CASE_ADD_PHOTO,
    CASE_DELETE_PHOTO,
    CASE_GET_PHOTOS,

    // GRADE CASES:
    CASE_GRADE
}
