CREATE DATABASE test;
CREATE USER ilya WITH PASSWORD '55_Rjhjkm_55';
GRANT ALL PRIVILEGES ON DATABASE test TO ilya;
GRANT ALL PRIVILEGES ON test       .* TO 'ilya'@'localhost' IDENTIFIED BY '55_Rjhjkm_55';
FLUSH PRIVILEGES;
ALTER TABLE test CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
   
